name: Launch Playwright tests

on:
  push:
    branches:
      - '**'

jobs:
  playwright-tests:
    env:
      HOME: /root
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.48.1-jammy
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Node JS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - name: Upload report to GitHub Actions Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
